dist: xenial
language: node_js

branches:
    except:
        - /^v[0-9]/

install:
    - npm ci

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - npm run build
    - npm run test-with-coverage

after_success:
    - npm run upload-coverage

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
    - provider: script
      script: npx semantic-release
      skip_cleanup: true
      on:
          tags: false
          branch: master
